/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   conversion_table.h                                 :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: ccabral <marvin@42.fr>                     +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2017/11/10 14:06:20 by ccabral           #+#    #+#             */
/*   Updated: 2019/02/27 14:27:10 by ccabral          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef CONVERSION_TABLE_H
# define CONVERSION_TABLE_H

# include "modifiers.h"
# include "percent.h"

t_function		g_functions[127] =
{
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&flag,
	&conversion,
	&conversion,
	&flag,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&star_field_width,
	&flag,
	&conversion,
	&flag,
	&precision,
	&conversion,
	&flag,
	&field_width,
	&field_width,
	&field_width,
	&field_width,
	&field_width,
	&field_width,
	&field_width,
	&field_width,
	&field_width,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&length,
	&conversion,
	&length,
	&conversion,
	&length,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&length,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
	&length,
	&conversion,
	&conversion,
	&conversion,
	&conversion,
};

#endif
